ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'TRIAGE_AREA';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'CLINICAL_ROOM';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'PROCEDURE_ROOM';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'LABORATORY';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'IMAGING_ROOM';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'FUNCTIONAL_EXPLORATION';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'EMPTY';
ALTER TYPE "ClinicalRoomType" ADD VALUE IF NOT EXISTS 'OTHER';

UPDATE "PhysicalRoom" SET "type" = 'TRIAGE_AREA' WHERE "type" = 'TRIAGE';
UPDATE "PhysicalRoom" SET "type" = 'CLINICAL_ROOM' WHERE "type" = 'CONSULTATION';
UPDATE "PhysicalRoom" SET "type" = 'PROCEDURE_ROOM' WHERE "type" = 'TREATMENT';
UPDATE "PhysicalRoom" SET "type" = 'LABORATORY' WHERE "type" = 'LAB';
UPDATE "PhysicalRoom" SET "type" = 'IMAGING_ROOM' WHERE "type" = 'IMAGING';
UPDATE "PhysicalRoom" SET "type" = 'OTHER' WHERE "type" = 'ADMIN';
