export enum PaymentTypeEnum {
  APPOINTMENT_PAYMENT = "APPOINTMENT_PAYMENT",
  APPOINTMENT_REFUND = "APPOINTMENT_REFUND",
  BOOKING_PAYMENT_2 = "BOOKING_PAYMENT_2",
  BOOKING_REFUND = "BOOKING_REFUND",
  ORDER_PAYMENT = "ORDER_PAYMENT",
  ORDER_REFUND = "ORDER_REFUND",
  WALLET_TOPUP = "WALLET_TOPUP",
  WALLET_WITHDRAW = "WALLET_WITHDRAW"
}
